include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
    avoid_returning_null_for_void: ignore
    use_full_hex_values_for_flutter_colors: ignore